-- Schema Identity & Access Management (IAM): User, Role, Permission (API resource: HTTP method +
-- URL pattern), Menu (cây, ĐỘC LẬP với Permission), UserRole, RolePermission, RoleMenu.
-- TÁCH RIÊNG khỏi schema nghiệp vụ (vd dev_e_commerce chỉ còn Product/UploadFile) để domain
-- User/Role/Permission/Menu độc lập hoàn toàn, dùng lại được cho project khác không cần đổi gì.
-- Không có Flyway/Liquibase trong repo này (xem CLAUDE.md) nên script này chỉ để tham khảo/tái tạo thủ công.
--
-- Thứ tự chạy: (1) phần CREATE USER — cần tài khoản DBA (system/sys); (2) phần CREATE TABLE — chạy
-- với chính user dev_iam; (3) phần GRANT — DBA cấp quyền cho user ứng dụng (vd "dev") đọc/ghi
-- dev_iam.* qua CÙNG MỘT datasource (Hibernate dùng @Table(schema="dev_iam") nên chỉ cần 1 connection
-- pool, không cần datasource thứ 2 — miễn user kết nối có đủ GRANT trên các bảng dev_iam.*); (4) phần
-- SEED — chạy với user ứng dụng hoặc dev_iam, tuỳ ai có quyền INSERT.
--
-- Thiết kế: role.data_scope là cột để dành cho việc mở rộng Data Permission trong tương lai
-- (ALL/SELF/DEPT/CUSTOM) - hiện tại CHƯA có logic lọc dữ liệu theo scope, chỉ lưu placeholder.
-- Quyền API (Permission) tách biệt hoàn toàn khỏi Menu: Menu chỉ phục vụ hiển thị điều hướng,
-- Permission chỉ phục vụ kiểm soát API (method + URL pattern kiểu Ant, khớp bằng AntPathMatcher).

-- ============================== (1) TẠO SCHEMA — chạy với system/sys ==============================
CREATE USER dev_iam IDENTIFIED BY "change-me" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO dev_iam;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO dev_iam;

-- ============================== (2) TẠO BẢNG — chạy với dev_iam ==============================

CREATE TABLE app_user (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR2(100) NOT NULL,
    password          VARCHAR2(255) NOT NULL,
    enabled           NUMBER(1)     DEFAULT 1 NOT NULL,
    -- Claim "sub" (UUID nội bộ, ổn định) của identity Keycloak đã đăng nhập lần đầu với username này
    -- (trust-on-first-use, xem JwtAuthenticationServiceImpl) — chặn 1 identity Keycloak KHÁC dùng
    -- preferred_username trùng tên "thừa kế" quyền của app_user này. NULL = chưa từng login qua Keycloak.
    keycloak_subject  VARCHAR2(255),
    created_at        TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_app_user_username UNIQUE (username),
    CONSTRAINT uk_app_user_keycloak_subject UNIQUE (keycloak_subject),
    CONSTRAINT ck_app_user_enabled CHECK (enabled IN (0, 1))
);

CREATE TABLE role (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key    VARCHAR2(50)  NOT NULL,
    role_name   VARCHAR2(100) NOT NULL,
    description VARCHAR2(255),
    data_scope  VARCHAR2(20)  DEFAULT 'ALL' NOT NULL,
    status      VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    sort_order  NUMBER(10)    DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_role_key UNIQUE (role_key)
);

-- code = định danh ổn định dùng với hasAuthority('PERM_' || code) trong @PreAuthorize.
-- http_method = GET/POST/PUT/PATCH/DELETE hoặc '*' (khớp mọi method). url_pattern kiểu Ant (/v1/x/**, /v1/x/*).
CREATE TABLE permission (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR2(100) NOT NULL,
    name         VARCHAR2(150) NOT NULL,
    http_method  VARCHAR2(10)  NOT NULL,
    url_pattern  VARCHAR2(255) NOT NULL,
    description  VARCHAR2(255),
    status       VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    created_at   TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at   TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_permission_code UNIQUE (code),
    CONSTRAINT uq_permission_resource UNIQUE (http_method, url_pattern)
);

-- Cây menu ĐỘC LẬP với Permission — chỉ phục vụ điều hướng UI. parent_id NULL = node gốc.
-- menu_type: DIRECTORY (thư mục chứa menu con, không có route) / MENU (có route, path+component) /
-- BUTTON (hành động UI mịn hơn menu, vd nút "Xoá" trong 1 trang - không tự có route riêng).
CREATE TABLE menu (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   NUMBER,
    name        VARCHAR2(100) NOT NULL,
    path        VARCHAR2(255),
    component   VARCHAR2(255),
    icon        VARCHAR2(100),
    menu_type   VARCHAR2(20)  NOT NULL,
    sort_order  NUMBER(10)    DEFAULT 0 NOT NULL,
    visible     NUMBER(1)     DEFAULT 1 NOT NULL,
    status      VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    created_at  TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_menu_parent FOREIGN KEY (parent_id) REFERENCES menu (id) ON DELETE CASCADE
);

CREATE INDEX idx_menu_parent ON menu (parent_id);

CREATE TABLE user_role (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    NUMBER NOT NULL,
    role_id    NUMBER NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE,
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id)
);

CREATE INDEX idx_user_role_user ON user_role (user_id);
CREATE INDEX idx_user_role_role ON user_role (role_id);

CREATE TABLE role_permission (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       NUMBER NOT NULL,
    permission_id NUMBER NOT NULL,
    created_at    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE,
    CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id)
);

CREATE INDEX idx_role_permission_role ON role_permission (role_id);

CREATE TABLE role_menu (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id    NUMBER NOT NULL,
    menu_id    NUMBER NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_role_menu_role FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_menu_menu FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE,
    CONSTRAINT uq_role_menu UNIQUE (role_id, menu_id)
);

CREATE INDEX idx_role_menu_role ON role_menu (role_id);

COMMIT;

-- ============================== (3) GRANT cho user ứng dụng — chạy với dev_iam ======================
-- Thay "dev" bằng user thật mà datasource ứng dụng (DB_DWH_USERNAME) dùng để kết nối.
GRANT SELECT, INSERT, UPDATE, DELETE ON app_user TO dev;
GRANT SELECT, INSERT, UPDATE, DELETE ON role TO dev;
GRANT SELECT, INSERT, UPDATE, DELETE ON permission TO dev;
GRANT SELECT, INSERT, UPDATE, DELETE ON menu TO dev;
GRANT SELECT, INSERT, UPDATE, DELETE ON user_role TO dev;
GRANT SELECT, INSERT, UPDATE, DELETE ON role_permission TO dev;
GRANT SELECT, INSERT, UPDATE, DELETE ON role_menu TO dev;

-- ============================== (4) SEED DATA — chạy với user ứng dụng (vd "dev") ====================
-- role_key phải khớp giá trị dùng trong claim "roles" của JWT (không có tiền tố ROLE_ — tiền tố
-- được JwtAuthenticationServiceImpl/JwtAuthenticationFilter tự thêm khi ánh xạ thành GrantedAuthority).

INSERT INTO dev_iam.role (role_key, role_name, description, data_scope, sort_order) VALUES
    ('ADMIN', 'Quản trị viên', 'Toàn quyền quản trị hệ thống', 'ALL', 1);
INSERT INTO dev_iam.role (role_key, role_name, description, data_scope, sort_order) VALUES
    ('USER', 'Người dùng', 'Người dùng thông thường, chỉ đọc dữ liệu công khai', 'SELF', 2);

-- Permission: khớp đúng các endpoint hiện có (xem controller/v1/ProductController, FileController).
-- rbac:manage (wildcard /v1/rbac/**) đã bao trùm toàn bộ API quản trị User/Role/Permission/Menu.
INSERT INTO dev_iam.permission (code, name, http_method, url_pattern, description) VALUES
    ('product:list', 'Xem danh sách sản phẩm', 'GET', '/v1/products', 'Liệt kê sản phẩm (phân trang)');
INSERT INTO dev_iam.permission (code, name, http_method, url_pattern, description) VALUES
    ('product:detail', 'Xem chi tiết sản phẩm', 'GET', '/v1/products/*', 'Xem 1 sản phẩm theo id');
INSERT INTO dev_iam.permission (code, name, http_method, url_pattern, description) VALUES
    ('product:create', 'Tạo sản phẩm', 'POST', '/v1/products', 'Tạo mới sản phẩm (kèm upload file)');
INSERT INTO dev_iam.permission (code, name, http_method, url_pattern, description) VALUES
    ('product:update', 'Cập nhật sản phẩm', 'PUT', '/v1/products/*', 'Sửa sản phẩm theo id');
INSERT INTO dev_iam.permission (code, name, http_method, url_pattern, description) VALUES
    ('product:delete', 'Xoá sản phẩm', 'DELETE', '/v1/products/*', 'Xoá sản phẩm theo id');
INSERT INTO dev_iam.permission (code, name, http_method, url_pattern, description) VALUES
    ('product:delete-file', 'Gỡ file khỏi sản phẩm', 'DELETE', '/v1/products/*/files/*', 'Gỡ 1 file khỏi gallery sản phẩm');
INSERT INTO dev_iam.permission (code, name, http_method, url_pattern, description) VALUES
    ('file:download', 'Tải file', 'GET', '/v1/files/*', 'Tải/xem 1 file đã upload theo id');
INSERT INTO dev_iam.permission (code, name, http_method, url_pattern, description) VALUES
    ('file:upload-init', 'Khởi tạo phiên upload', 'POST', '/v1/files/uploads', 'Bắt đầu 1 phiên upload theo chunk');
INSERT INTO dev_iam.permission (code, name, http_method, url_pattern, description) VALUES
    ('file:upload-chunk', 'Upload 1 chunk', 'PUT', '/v1/files/uploads/*/chunks/*', 'Ghi 1 đoạn (chunk) file');
INSERT INTO dev_iam.permission (code, name, http_method, url_pattern, description) VALUES
    ('file:upload-complete', 'Hoàn tất upload', 'POST', '/v1/files/uploads/*/complete', 'Ghép các chunk thành file hoàn chỉnh');
INSERT INTO dev_iam.permission (code, name, http_method, url_pattern, description) VALUES
    ('file:upload-delete', 'Huỷ phiên upload', 'DELETE', '/v1/files/uploads/*', 'Huỷ 1 phiên upload đang dang dở');
INSERT INTO dev_iam.permission (code, name, http_method, url_pattern, description) VALUES
    ('rbac:manage', 'Quản trị IAM', '*', '/v1/rbac/**', 'Toàn quyền quản lý user/role/permission/menu');

-- ADMIN: toàn bộ permission hiện có.
INSERT INTO dev_iam.role_permission (role_id, permission_id)
    SELECT r.id, p.id FROM dev_iam.role r CROSS JOIN dev_iam.permission p
    WHERE r.role_key = 'ADMIN';

-- USER: chỉ đọc (list/detail sản phẩm + tải file).
INSERT INTO dev_iam.role_permission (role_id, permission_id)
    SELECT r.id, p.id FROM dev_iam.role r CROSS JOIN dev_iam.permission p
    WHERE r.role_key = 'USER' AND p.code IN ('product:list', 'product:detail', 'file:download');

-- Menu mẫu: nhóm "Hệ thống" (quản trị IAM) + "Sản phẩm".
INSERT INTO dev_iam.menu (parent_id, name, path, component, icon, menu_type, sort_order) VALUES
    (NULL, 'Hệ thống', '/system', NULL, 'settings', 'DIRECTORY', 1);
INSERT INTO dev_iam.menu (parent_id, name, path, component, icon, menu_type, sort_order)
    SELECT id, 'Người dùng', '/system/user', 'system/user/user-list', 'person', 'MENU', 1
    FROM dev_iam.menu WHERE name = 'Hệ thống' AND parent_id IS NULL;
INSERT INTO dev_iam.menu (parent_id, name, path, component, icon, menu_type, sort_order)
    SELECT id, 'Vai trò', '/system/role', 'system/role/role-list', 'badge', 'MENU', 2
    FROM dev_iam.menu WHERE name = 'Hệ thống' AND parent_id IS NULL;
INSERT INTO dev_iam.menu (parent_id, name, path, component, icon, menu_type, sort_order)
    SELECT id, 'Menu', '/system/menu', 'system/menu/menu-list', 'menu', 'MENU', 3
    FROM dev_iam.menu WHERE name = 'Hệ thống' AND parent_id IS NULL;
INSERT INTO dev_iam.menu (parent_id, name, path, component, icon, menu_type, sort_order)
    SELECT id, 'Quyền', '/system/permission', 'system/permission/permission-list', 'lock', 'MENU', 4
    FROM dev_iam.menu WHERE name = 'Hệ thống' AND parent_id IS NULL;
INSERT INTO dev_iam.menu (parent_id, name, path, component, icon, menu_type, sort_order) VALUES
    (NULL, 'Sản phẩm', '/products', 'products/product-list', 'inventory', 'MENU', 2);

-- ADMIN thấy toàn bộ menu; USER chỉ thấy "Sản phẩm".
INSERT INTO dev_iam.role_menu (role_id, menu_id)
    SELECT r.id, m.id FROM dev_iam.role r CROSS JOIN dev_iam.menu m
    WHERE r.role_key = 'ADMIN';
INSERT INTO dev_iam.role_menu (role_id, menu_id)
    SELECT r.id, m.id FROM dev_iam.role r CROSS JOIN dev_iam.menu m
    WHERE r.role_key = 'USER' AND m.name = 'Sản phẩm';

-- Tạo user & gán role: dùng API thay vì INSERT tay — xem UserController (POST /v1/rbac/users) và
-- UserRoleController (PUT /v1/rbac/users/{userId}/roles).

COMMIT;
