services:
  redis-node-0:
    image: redis:7-alpine
    ports:
      - "7000:7000"
      - "17000:17000"
    volumes:
      - redis-cluster_data-0:/data
    command: >
      redis-server
      --port 7000
      --cluster-enabled yes
      --cluster-config-file nodes-7000.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --requirepass Hieu123456789a
      --masterauth Hieu123456789a
      --cluster-announce-ip 192.168.1.3
      --cluster-announce-port 7000
      --cluster-announce-bus-port 17000
      --dir /data

  redis-node-1:
    image: redis:7-alpine
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - redis-cluster_data-1:/data
    command: >
      redis-server
      --port 7001
      --cluster-enabled yes
      --cluster-config-file nodes-7001.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --requirepass Hieu123456789a
      --masterauth Hieu123456789a
      --cluster-announce-ip 192.168.1.3
      --cluster-announce-port 7001
      --cluster-announce-bus-port 17001
      --dir /data

  redis-node-2:
    image: redis:7-alpine
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - redis-cluster_data-2:/data
    command: >
      redis-server
      --port 7002
      --cluster-enabled yes
      --cluster-config-file nodes-7002.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --requirepass Hieu123456789a
      --masterauth Hieu123456789a
      --cluster-announce-ip 192.168.1.3
      --cluster-announce-port 7002
      --cluster-announce-bus-port 17002
      --dir /data

  redis-node-3:
    image: redis:7-alpine
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - redis-cluster_data-3:/data
    command: >
      redis-server
      --port 7003
      --cluster-enabled yes
      --cluster-config-file nodes-7003.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --requirepass Hieu123456789a
      --masterauth Hieu123456789a
      --cluster-announce-ip 192.168.1.3
      --cluster-announce-port 7003
      --cluster-announce-bus-port 17003
      --dir /data

  redis-node-4:
    image: redis:7-alpine
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
      - redis-cluster_data-4:/data
    command: >
      redis-server
      --port 7004
      --cluster-enabled yes
      --cluster-config-file nodes-7004.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --requirepass Hieu123456789a
      --masterauth Hieu123456789a
      --cluster-announce-ip 192.168.1.3
      --cluster-announce-port 7004
      --cluster-announce-bus-port 17004
      --dir /data

  redis-node-5:
    image: redis:7-alpine
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
      - redis-cluster_data-5:/data
    command: >
      redis-server
      --port 7005
      --cluster-enabled yes
      --cluster-config-file nodes-7005.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --requirepass Hieu123456789a
      --masterauth Hieu123456789a
      --cluster-announce-ip 192.168.1.3
      --cluster-announce-port 7005
      --cluster-announce-bus-port 17005
      --dir /data

volumes:
  redis-cluster_data-0:
  redis-cluster_data-1:
  redis-cluster_data-2:
  redis-cluster_data-3:
  redis-cluster_data-4:
  redis-cluster_data-5:
