services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=dev'
      - 'MONGO_INITDB_ROOT_PASSWORD=Hieu123456789a'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
